on:
#  push:
#    branches: latest
#  pull_request:
#    branches: latest
  schedule:
    - cron: '0 3 * * 0'
  workflow_dispatch:
    branches: latest
   
name: 'Shellcheck'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
